# NumPy — Beginner Notebook

## What is NumPy?

NumPy is a Python library that makes it easier to work with numbers and numerical data.

It is commonly used in Data Science, AI, and Machine Learning.

We will start with very simple examples.


## 1. Import NumPy

Before using NumPy, we import it:

```python
import numpy as np
```

`np` is simply a short name for NumPy.


In [1]:
import numpy as np


In [7]:
scores = [50, 60, 70, 80, 90]

new_scores = []

for score in scores:
    new_scores.append(score + 5)

print(new_scores)

[55, 65, 75, 85, 95]


In [4]:
import numpy as np

scores = np.array([50, 60, 70, 80, 90])

new_scores = scores + 5

print(new_scores)

[55 65 75 85 95]


             Study   Attendance   Previous
Student 1      2        60           45
Student 2      4        70           55
Student 3      6        80           65
Student 4      8        90           75

In [ ]:
#              Study   Attendance   Previous
# Student 1      2        60           45
# Student 2      4        70           55
# Student 3      6        80           65
# Student 4      8        90           75  

## 2. Create a NumPy array

You already know Python lists:

```python
scores = [50, 60, 70, 80, 90]
```

We can create a NumPy array using `np.array()`.

An array is useful for working with numerical data.


In [8]:
scores = np.array([50, 60, 70, 80, 90])

print(scores)


[50 60 70 80 90]


In [9]:
import numpy as np

scores = np.array([50, 60, 70, 80, 90])

print(scores + 5)
print(scores.mean())
print(scores.max())
print(scores.min())

[55 65 75 85 95]
70.0
90
50


## 3. Indexing

NumPy arrays use indexing like Python lists.

For this array:

```text
50 → index 0
60 → index 1
70 → index 2
80 → index 3
90 → index 4
```


In [10]:
scores = np.array([50, 60, 70, 80, 90])

print(scores[0])
print(scores[2])
print(scores[-1])

50
70
90


## 4. Calculate on all the numbers

One useful feature is that we can perform an operation on the whole array.

If every student gets 5 extra marks:

```python
scores + 5
```

NumPy adds 5 to every score.


In [ ]:
scores = np.array([50, 60, 70, 80, 90])

new_scores = scores + 5

print(new_scores)


## 5. Multiplication

We can also multiply every value.

For example, if prices are doubled:


In [11]:
prices = np.array([100, 200, 300])

new_prices = prices * 2

print(new_prices)


[200 400 600]


## 6. Useful NumPy calculations

Some useful operations are:

- `.sum()` → total
- `.mean()` → average
- `.max()` → highest
- `.min()` → lowest


In [12]:
scores = np.array([50, 60, 70, 80, 90])

print("Total:", scores.sum())
print("Average:", scores.mean())
print("Highest:", scores.max())
print("Lowest:", scores.min())


Total: 350
Average: 70.0
Highest: 90
Lowest: 50


## 7. Slicing

Slicing works like Python lists.

```python
scores[1:4]
```

means start at index 1 and stop before index 4.


In [ ]:
scores = np.array([50, 60, 70, 80, 90])

print(scores[1:4])

[60 70 80]


## 8. AI/ML example

Imagine these are students' study hours and exam scores.

```python
study_hours = np.array([2, 4, 6, 8, 10])
exam_scores = np.array([45, 55, 65, 75, 85])
```

NumPy lets us quickly calculate information from this numerical data.


In [ ]:
study_hours = np.array([2, 4, 6, 8, 10])
exam_scores = np.array([45, 55, 65, 75, 85])

print("Average study hours:", study_hours.mean())
print("Average exam score:", exam_scores.mean())
print("Highest exam score:", exam_scores.max())


## 9. Two-dimensional arrays

Think of a small spreadsheet:

```text
Study Hours    Score
4              60
6              75
8              85
```

In NumPy, we can represent this with rows and columns.


In [ ]:
students = np.array([
    [4, 60],
    [6, 75],
    [8, 85]
])

print(students)


[[ 4 60]
 [ 6 75]
 [ 8 85]]


# Class Activity 1 — Very Easy

Create:

```python
numbers = np.array([10, 20, 30, 40, 50])
```

Print:

1. First number
2. Last number
3. Highest number
4. Lowest number


# Class Activity 2 — Easy

Create:

```python
scores = np.array([50, 60, 70, 80, 90])
```

Find:

1. Total
2. Average
3. Highest score
4. Lowest score


# Class Activity 3 — Easy

Create:

```python
prices = np.array([100, 200, 300, 400])
```

Increase every price by 50.

Expected:

```text
[150 250 350 450]
```


# Class Activity 4 — AI/ML

Create:

```python
study_hours = np.array([2, 4, 6, 8, 10])
scores = np.array([45, 55, 65, 75, 85])
```

Find:

1. Average study time
2. Average score
3. Highest score
4. Lowest score
5. Add 5 marks to every score
6. Find the new average


# Class Activity 5 — Slightly harder

Given:

```python
scores = np.array([45, 67, 82, 39, 91, 55, 73])
```

Find:

1. Average
2. Highest score
3. Lowest score
4. A new array with 3 marks added to every score
5. Average of the new scores


# Summary

Useful NumPy operations:

```python
scores[0]       # indexing
scores[1:3]     # slicing
scores + 5      # add to every value
scores * 2      # multiply every value
scores.sum()    # total
scores.mean()   # average
scores.max()    # highest
scores.min()    # lowest
```

> NumPy helps us work with numerical data efficiently, which is why it is commonly used in Data Science, AI, and Machine Learning.
